version: '3.8'
services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - ollama
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=chatdb
      - DB_USER=yourusername
      - DB_PASS=yourpassword
      - DB_PORT=5432
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: stratis77
      POSTGRES_PASSWORD: Heierlark321?
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ollama:  
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  pgdata:
  ollama_data:

